services:
  - type: web
    name: easyleave-backend
    env: node
    repo: https://github.com/Junaid2002/easyLeave
    branch: main
    buildCommand: cd Backend && npm install && ls -la models/
    startCommand: cd Backend && ls -la models/ && node index.js
    plan: free
    autoDeploy: true
    include:
      - Backend/**  # Include all files in Backend and subdirectories