services:
  - type: web
    name: easyleave-backend
    env: node:18.20.2
    repo: https://github.com/Junaid2002/easyLeave
    branch: main
    buildCommand: |
      cd Backend
      npm install
      ls -la models/
    startCommand: |
      cd Backend
      node index.js
    plan: free
    autoDeploy: true
    include:
      - Backend/**
